/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControllerCurtida;
import controller.ControllerMusica;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Musica;
import model.Usuario;


/**
 *
 * @author Junior
 */
public class HomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public HomeFrame(Usuario usuarioLogado) {
        initComponents();

        this.usuarioLogado = usuarioLogado;
        cm = new ControllerMusica(this);
        
        DefaultTableModel tableMusicas = new DefaultTableModel();
        
        tableMusicas.addColumn("ID");
        tableMusicas.addColumn("Nome");
        tableMusicas.addColumn("Gênero");
        tableMusicas.addColumn("Artista");
        tableMusicas.addColumn("Curtidas");
        tableMusicas.addColumn("Descurtidas");
        tbl_musicas.setModel(tableMusicas);
        
        DefaultTableModel tableCurtidas = new DefaultTableModel();
        tableCurtidas.addColumn("ID");
        tableCurtidas.addColumn("Nome");
        tableCurtidas.addColumn("Gênero");
        tableCurtidas.addColumn("Artista");
        tbl_curtidas.setModel(tableCurtidas);
        
        DefaultTableModel tableDescurtidas = new DefaultTableModel();
        tableDescurtidas.addColumn("ID");
        tableDescurtidas.addColumn("Nome");
        tableDescurtidas.addColumn("Gênero");
        tableDescurtidas.addColumn("Artista");

        tbl_descurtidas.setModel(tableDescurtidas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Buscar = new javax.swing.JPanel();
        txt_nome_buscar = new javax.swing.JTextField();
        bt_buscar = new javax.swing.JButton();
        lbl_buscar_home = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_musicas = new javax.swing.JTable();
        bt_curtir = new javax.swing.JButton();
        bt_descurtir = new javax.swing.JButton();
        Curtidas = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_curtidas = new javax.swing.JTable();
        lbl_musicas_curtidas = new javax.swing.JLabel();
        bt_atualizar_curtidas = new javax.swing.JButton();
        Descurtidas = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_descurtidas = new javax.swing.JTable();
        lbl_musicas_descurtidas = new javax.swing.JLabel();
        bt_atualizar_descurtidas = new javax.swing.JButton();
        Historico = new javax.swing.JPanel();
        Playlists = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt_buscar.setText("Buscar");
        bt_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_buscarActionPerformed(evt);
            }
        });

        lbl_buscar_home.setText("Buscar Músicas");

        tbl_musicas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_musicas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_musicasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_musicas);

        bt_curtir.setText("👍");
        bt_curtir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_curtirActionPerformed(evt);
            }
        });

        bt_descurtir.setText("👎");
        bt_descurtir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_descurtirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BuscarLayout = new javax.swing.GroupLayout(Buscar);
        Buscar.setLayout(BuscarLayout);
        BuscarLayout.setHorizontalGroup(
            BuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscarLayout.createSequentialGroup()
                .addGroup(BuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BuscarLayout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addComponent(bt_curtir)
                        .addGap(140, 140, 140)
                        .addComponent(bt_descurtir))
                    .addGroup(BuscarLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BuscarLayout.createSequentialGroup()
                        .addGap(423, 423, 423)
                        .addComponent(bt_buscar))
                    .addGroup(BuscarLayout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(txt_nome_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BuscarLayout.createSequentialGroup()
                        .addGap(419, 419, 419)
                        .addComponent(lbl_buscar_home)))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        BuscarLayout.setVerticalGroup(
            BuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lbl_buscar_home)
                .addGap(18, 18, 18)
                .addComponent(txt_nome_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(bt_buscar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(BuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_curtir)
                    .addComponent(bt_descurtir))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Buscar", Buscar);

        tbl_curtidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_curtidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_curtidasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_curtidas);

        lbl_musicas_curtidas.setText("Musicas curtidas");

        bt_atualizar_curtidas.setText("Atualizar");
        bt_atualizar_curtidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_atualizar_curtidasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CurtidasLayout = new javax.swing.GroupLayout(Curtidas);
        Curtidas.setLayout(CurtidasLayout);
        CurtidasLayout.setHorizontalGroup(
            CurtidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CurtidasLayout.createSequentialGroup()
                .addGroup(CurtidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CurtidasLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CurtidasLayout.createSequentialGroup()
                        .addGap(412, 412, 412)
                        .addComponent(lbl_musicas_curtidas))
                    .addGroup(CurtidasLayout.createSequentialGroup()
                        .addGap(421, 421, 421)
                        .addComponent(bt_atualizar_curtidas)))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        CurtidasLayout.setVerticalGroup(
            CurtidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CurtidasLayout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addComponent(lbl_musicas_curtidas)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(bt_atualizar_curtidas)
                .addGap(119, 119, 119))
        );

        jTabbedPane1.addTab("Curtidas", Curtidas);

        Descurtidas.setVerifyInputWhenFocusTarget(false);

        tbl_descurtidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_descurtidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_descurtidasMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbl_descurtidas);

        lbl_musicas_descurtidas.setText("Músicas descurtidas");

        bt_atualizar_descurtidas.setText("Atualizar");
        bt_atualizar_descurtidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_atualizar_descurtidasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DescurtidasLayout = new javax.swing.GroupLayout(Descurtidas);
        Descurtidas.setLayout(DescurtidasLayout);
        DescurtidasLayout.setHorizontalGroup(
            DescurtidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DescurtidasLayout.createSequentialGroup()
                .addGroup(DescurtidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DescurtidasLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DescurtidasLayout.createSequentialGroup()
                        .addGap(407, 407, 407)
                        .addComponent(lbl_musicas_descurtidas))
                    .addGroup(DescurtidasLayout.createSequentialGroup()
                        .addGap(423, 423, 423)
                        .addComponent(bt_atualizar_descurtidas)))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        DescurtidasLayout.setVerticalGroup(
            DescurtidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DescurtidasLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(lbl_musicas_descurtidas)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(bt_atualizar_descurtidas)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Descurtidas", Descurtidas);

        javax.swing.GroupLayout HistoricoLayout = new javax.swing.GroupLayout(Historico);
        Historico.setLayout(HistoricoLayout);
        HistoricoLayout.setHorizontalGroup(
            HistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        HistoricoLayout.setVerticalGroup(
            HistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Historico", Historico);

        javax.swing.GroupLayout PlaylistsLayout = new javax.swing.GroupLayout(Playlists);
        Playlists.setLayout(PlaylistsLayout);
        PlaylistsLayout.setHorizontalGroup(
            PlaylistsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        PlaylistsLayout.setVerticalGroup(
            PlaylistsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Playlists", Playlists);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_descurtirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_descurtirActionPerformed
        int linha = tbl_musicas.getSelectedRow();

        if (linha != -1) {
            int musicaId = (int) tbl_musicas.getValueAt(linha, 0);
            int usuarioId = usuarioLogado.getId();

            ControllerCurtida.descurtir(usuarioId, musicaId);
            JOptionPane.showMessageDialog(this, "Música descurtida.");

            bt_buscar.doClick();
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma música na tabela primeiro.");
        }
    }//GEN-LAST:event_bt_descurtirActionPerformed

    private void bt_curtirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_curtirActionPerformed
        int linha = tbl_musicas.getSelectedRow();

        if (linha != -1) {
            int musicaId = (int) tbl_musicas.getValueAt(linha, 0); // coluna 0 = ID
            int usuarioId = usuarioLogado.getId(); // ou como você estiver armazenando o usuário

            ControllerCurtida.curtir(usuarioId, musicaId);
            JOptionPane.showMessageDialog(this, "Música curtida com sucesso!");

            bt_buscar.doClick();
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma música na tabela primeiro.");
        }
    }//GEN-LAST:event_bt_curtirActionPerformed

    private void tbl_musicasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_musicasMouseClicked
        int linha = tbl_musicas.getSelectedRow();
        if (linha != -1) {
            int musicaId = (int) tbl_musicas.getValueAt(linha, 0);
            int usuarioId = usuarioLogado.getId();

            boolean curtiu = ControllerCurtida.usuarioCurtiu(usuarioId, musicaId);

            if (curtiu) {
                JOptionPane.showMessageDialog(this, "❤️ Você já curtiu esta música!");
            }
        }
    }//GEN-LAST:event_tbl_musicasMouseClicked

    private void bt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_buscarActionPerformed
        String busca = txt_nome_buscar.getText();
        List<Musica> musicas = cm.buscarMusica(busca);

        DefaultTableModel modelo = (DefaultTableModel) tbl_musicas.getModel();
        modelo.setRowCount(0);

        if (musicas == null || musicas.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Música não encontrada!",
                "Aviso",
                JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        for (Musica m : musicas) {
            modelo.addRow(new Object[] {
                m.getId(),
                m.getNome(),
                m.getGenero(),
                m.getArtista().getNome(),
                m.getCurtidas(),
                m.getDescurtidas()

            });
        }

    }//GEN-LAST:event_bt_buscarActionPerformed

    private void tbl_curtidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_curtidasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_curtidasMouseClicked

    private void bt_atualizar_curtidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_atualizar_curtidasActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tbl_curtidas.getModel();
        modelo.setRowCount(0);

        List<Musica> curtidas = cm.listarCurtidas(usuarioLogado.getId());

        for (Musica m : curtidas) {
            modelo.addRow(new Object[]{
                m.getId(),
                m.getNome(),
                m.getGenero(),
                m.getArtista().getNome()
            });
        }
    }//GEN-LAST:event_bt_atualizar_curtidasActionPerformed

    private void tbl_descurtidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_descurtidasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_descurtidasMouseClicked

    private void bt_atualizar_descurtidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_atualizar_descurtidasActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tbl_descurtidas.getModel();
        modelo.setRowCount(0);

        List<Musica> descurtidas = cm.listarDescurtidas(usuarioLogado.getId());

        for (Musica m : descurtidas) {
            modelo.addRow(new Object[]{
                m.getId(),
                m.getNome(),
                m.getGenero(),
                m.getArtista().getNome()
            });
        }
    }//GEN-LAST:event_bt_atualizar_descurtidasActionPerformed

    /**
     * @param args the command line arguments
     */
    
//Comentando o main pra nao ser possivel entrar na home sem um usuario
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new HomeFrame().setVisible(true);
//            }
//        });
//    }
    
    
    private ControllerMusica cm;
    private Usuario usuarioLogado;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Buscar;
    private javax.swing.JPanel Curtidas;
    private javax.swing.JPanel Descurtidas;
    private javax.swing.JPanel Historico;
    private javax.swing.JPanel Playlists;
    private javax.swing.JButton bt_atualizar_curtidas;
    private javax.swing.JButton bt_atualizar_descurtidas;
    private javax.swing.JButton bt_buscar;
    private javax.swing.JButton bt_curtir;
    private javax.swing.JButton bt_descurtir;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_buscar_home;
    private javax.swing.JLabel lbl_musicas_curtidas;
    private javax.swing.JLabel lbl_musicas_descurtidas;
    private javax.swing.JTable tbl_curtidas;
    private javax.swing.JTable tbl_descurtidas;
    private javax.swing.JTable tbl_musicas;
    private javax.swing.JTextField txt_nome_buscar;
    // End of variables declaration//GEN-END:variables
}
